# -*- coding: utf-8 -*-
"""boston.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxvglDHurI8uK8Z3re2MAHRpTX8i5_oJ
"""

import pandas as pd
import numpy as np

data=pd.read_csv("BostonHousing.csv")

data.head()

data.tail()

data.info()

data.columns

data.head(10)

data.shape

data.isnull().sum()

data.describe()

import seaborn as sns

!pip install tensorflow

import pandas as pd

# Load dataset from CSV file
df = pd.read_csv('BostonHousing.csv')

# Display first 5 rows
print(df.head())

from sklearn.preprocessing import StandardScaler

# Split data into input and output variables
X = df.drop('medv', axis=1)
y = df['medv']

# Feature Scaling
scaler = StandardScaler()

X = scaler.fit_transform(X)

# Display first 5 rows of scaled data
print(X[:5])

from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

# Print shapes
print("Training set shape:", X_train.shape, y_train.shape)
print("Testing set shape:", X_test.shape, y_test.shape)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout


# Define model
model = Sequential()

# Input + Hidden Layer
model.add(Dense(64, input_dim=13, activation='relu'))

# Dropout Layer
model.add(Dropout(0.2))

# Hidden Layer
model.add(Dense(32, activation='relu'))

# Output Layer
model.add(Dense(1))

# Display model summary
print(model.summary())

# Compile model
model.compile(
    loss='mean_squared_error',
    optimizer='adam',
    metrics=['mean_absolute_error']
)

from keras.callbacks import EarlyStopping

# Early stopping
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=5
)

# Train model
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[early_stopping]
)

import matplotlib.pyplot as plt

# Plot loss graph
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title('Model Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')

plt.legend(['Training', 'Validation'])

plt.show()

# Evaluate model
loss, mae = model.evaluate(X_test, y_test)

# Print Mean Absolute Error
print("Mean Absolute Error:", mae)