# -*- coding: utf-8 -*-
"""google.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11emrjDr8gwXoprqa1mevqbQW-Trm-uEW
"""

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout

# Load the dataset
data = pd.read_csv('GOOGL.csv')

print(data.head())

# Extract the 'Open' column
dataset = data['Open'].values.reshape(-1, 1)

print(data.head())
print(data.columns)

# Extract Open column
dataset = data[['Open']]

# Convert to numeric
dataset['Open'] = pd.to_numeric(dataset['Open'], errors='coerce')

# Remove invalid values
dataset.dropna(inplace=True)

# Convert to numpy array
dataset = dataset.values

# Scale the data between 0 and 1
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)

# Create training and testing datasets
training_data_len = int(len(dataset) * 0.8)

training_data = dataset[:training_data_len]
testing_data = dataset[training_data_len:]

# Function to create dataset
def create_dataset(dataset, time_step=1):
    X = []
    Y = []

    for i in range(len(dataset) - time_step - 1):
        X.append(dataset[i:(i + time_step), 0])
        Y.append(dataset[i + time_step, 0])

    return np.array(X), np.array(Y)

# Create datasets with time step of 60 days
time_step = 60

X_train, Y_train = create_dataset(training_data, time_step)
X_test, Y_test = create_dataset(testing_data, time_step)

# Reshape input to be [samples, time steps, features]
X_train = np.reshape(X_train,
                     (X_train.shape[0], X_train.shape[1], 1))

X_test = np.reshape(X_test,
                    (X_test.shape[0], X_test.shape[1], 1))

# Create the RNN model
model = Sequential()

# First LSTM layer
model.add(LSTM(units=50,
               return_sequences=True,
               input_shape=(X_train.shape[1], 1)))

model.add(Dropout(0.2))

# Second LSTM layer
model.add(LSTM(units=50,
               return_sequences=True))

model.add(Dropout(0.2))

# Third LSTM layer
model.add(LSTM(units=50))

model.add(Dropout(0.2))

# Output layer
model.add(Dense(units=1))

# Compile the model
model.compile(optimizer='adam',
              loss='mean_squared_error')

# Train the model
model.fit(X_train,
          Y_train,
          epochs=100,
          batch_size=32)

# Predict stock prices
predictions = model.predict(X_test)

# Inverse transform predictions
predictions = scaler.inverse_transform(predictions)

# Inverse transform actual values
Y_test_actual = scaler.inverse_transform(
    Y_test.reshape(-1, 1)
)

# Plot the results
plt.figure(figsize=(10,6))

plt.plot(Y_test_actual,
         color='blue',
         label='Actual Google Stock Price')

plt.plot(predictions,
         color='red',
         label='Predicted Google Stock Price')

plt.title('Google Stock Price Prediction using RNN')
plt.xlabel('Time')
plt.ylabel('Google Stock Price')
plt.legend()

plt.show()